### PR TITLE
Support macOS 13 Ventura

### PR DESCRIPTION
**Pull request by devinea**
Would be great if this can be merged and a new version of insight released.

### CODE REVIEW

**Comment by AlexSwensen** [comment]
Sadly its a little more cumbersome than just that.

See [here](https://github.com/yeoman/yo/issues/753#issuecomment-1279830102) for details.

If you are having issues trying to run `yo` in Ventura, you can follow [these](https://github.com/yeoman/yo/issues/753#issuecomment-1302569839) workaround instructions.

**Comment by devinea** [comment]
@AlexSwensen Great that another fix in progress. I'll close this.

**Comment by mischah** [comment]
Released a fix with [v4.3.1](https://www.npmjs.com/package/yo/v/4.3.1) :octocat:

**Comment by rprieto** [comment]
Hi @AlexSwensen. Is there a plan to support macOS Ventura?
It seems that the fix above was to temporarily remove `insights` from `yo`, is that right?
I'm asking because this also impacts any other tool using `insights`.

Thank you

**Comment by AlexSwensen** [comment]
> Hi @AlexSwensen. Is there a plan to support macOS Ventura?
> 
> It seems that the fix above was to temporarily remove `insights` from `yo`, is that right?
> 
> I'm asking because this also impacts any other tool using `insights`.
> 
> 
> 
> Thank you


From what I understand, that is correct. I would go to the main yo repo to ask for more details on this. I left a link in my original comment above.

**Comment by rprieto** [comment]
Thanks. I don’t actually use `yo` itself. This is about Thumbsup that uses `insights` directly for analytics, and which doesn’t build on macOS Ventura anymore.

https://github.com/thumbsup/thumbsup/issues/322

**Comment by AlexSwensen** [comment]
@rprieto In that case I would either open a new issue, or fork the package and patch it. The workarounds in those same links should work for you.

**Comment by rprieto** [comment]
Thanks @AlexSwensen. I'm happy to open a new issue - or could we reopen this one? It is called `Support macOS 13 Ventura` which seems appropriate. I understand the workaround was for `yo` not to use Insights anymore, but that didn't really fix this issue. Otherwise thank you I will look at forking it.

**Comment by mischah** [comment]
Opened a new issue to address this which mentions the work that is to do fix this. 
See #83

**Pull request closed without merging**
