### PR TITLE
Replace `request` with `got`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
The only thing that isn't working is Yandex, which 404's.  I couldn't find any documentation on it; does anybody have any pointers on that?

### CODE REVIEW

**Comment by sindresorhus** [comment]
@wtgtybhertgeghgtwtg Still interested in finishing this? Got has had a major version since this, so it might be easier now.

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you for reminding me.  Are there any integration tests for this?

**Comment by sindresorhus** [comment]
Integration tests for this module, you mean? Unfortunately not.

**Comment by wtgtybhertgeghgtwtg** [comment]
Short of that, the PR is prepared.

**Comment by Hypnosphi** [comment]
@sindresorhus what are current plans for replacing the deprecated `request` package? I can open a new PR

https://github.com/request/request/issues/3142

**Pull request closed without merging**
